config/routes.rb
Rails.application.routes.draw do

  
  root to:             'static_pages#home'

  get  'o-udruzi'  =>  'static_pages#about',    as: :about
  get  'statut'    =>  'static_pages#statut',   as: :statut
  get  'kontakt'   =>  'contacts#new',  as: :contact
  get  'vijesti'   =>  'static_pages#posts',    as: :news
  get  'vijest/:id'=>  'static_pages#single_post'
 
  resources :contacts, only: [:new, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "users/registrations" }

  devise_scope :user do
    get   'uredi',        to: 'users/registrations#edit',  as: :edit
    get   'registracija', to: 'users/registrations#new',   as: :register
    get   'prijava' ,     to: 'users/sessions#new',        as: :login
    get   'odjava' ,      to: 'users/sessions#destroy',    as: :logout
    get   'prikaz',       to: 'users#show_profile',        as: :show_profile
  end

  devise_for :admins, :controllers => {:sessions => "admins_sessions"}  
  
  devise_scope :admin do
    
    get   'korisnici',        to: 'admins#index',          as: :admin_root
    get   'korisnik/ukloni',  to: 'admins#delete',         as: :admin_delete
    post  'korisnik/unisti',  to: 'admins#destroy',        as: :admin_destroy  
    get   'korisnik/:id',     to: 'admins#show',           as: :admin_show 

    get   'admin/prijava',    to: 'admins_sessions#new',      as: :admin_login 
    get   'admin/odjava',     to: 'admins_sessions#destroy',  as: :admin_logout 

  end

  get   'vijesti-pregled',      to: 'posts#index',    as: :posts
  get   'vijest-pregled/:id',   to: 'posts#show',     as: :post_show
  get   'vijest-ukloni/:id',    to: 'posts#delete',   as: :post_delete
  get   'vijest-uredi/:id',     to: 'posts#edit',     as: :post_edit
  get   'vijest-nova',          to: 'posts#new',      as: :post_new
  post  'vijest-stvori',        to: 'posts#create',   as: :post_create
  post  'vijest-uredi',         to: 'posts#update',   as: :post_update
  post  'vijest-unisti/:id',    to: 'posts#destroy',  as: :post_destroy

end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-default visible-xs">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">AMA ETFOS</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class=<%= 'active' if current_page?(admin_root_path) %>><%= link_to "Korisnici", admin_root_path %></li>
        <li class=<%= 'active' if current_page?(posts_path) %>><%= link_to "Vijesti", posts_path %></li>
        <li class=<%= 'active' if current_page?('#') %>><%= link_to "Pretplatnici", '#' %></li>
        <li><%= link_to "Kraj rada", admin_logout_path %></li>
      </ul>
    </div>
  </div>
</nav>


<div class="container-fluid admin-side">
  <div class="row content">
    <div class="col-sm-3 col-lg-2 sidenav hidden-xs">
      <div class='brand'>
        <h2><%= image_tag 'logo_brand_white.svg', :class => 'logo-sidenav' %>AMA</h2>
      </div>
      <ul class="nav nav-pills nav-stacked">
        <li><a href="#">
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
          <%= current_admin.email %></a>
        </li>
        
        <li class=<%= 'active' if current_page?(admin_root_path) %>>
          <%= link_to admin_root_path do%>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            Korisnici
          <% end %>
        </li>
        
        <li class=<%= 'active' if current_page?(posts_path) %>>
          <%= link_to posts_path do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Vijesti
          <% end %>
        </li>
        
        <li class=<%= 'active' if current_page?('#') %>>
          <%= link_to '#' do %>
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            Pretplatnici
          <% end %>
        </li>
        
        <li>
          <%= link_to admin_logout_path do %>
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
            Kraj rada
          <% end %>
        </li>

      </ul><br>
    </div>
    <br>

    <div class="col-sm-8 col-lg-9 col-sm-offset-3 col-lg-offset-2 workspace">
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%=key%>">
          <%= value %>
      </div>
    <% end %>

app/views/layouts/_footer.html.erb
<% unless (current_page?(register_path) || current_page?(login_path) || current_page?(new_user_session_path) || current_page?(user_session_path)) %>
<section class="footer">
<!--
<%= form_for @contact do |f| %>

  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, autofocus: true, required: :true, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %><br/>
    <%= f.email_field :email, autofocus: true, required: :true, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :message %><br/>
    <%= f.text_area :message, autofocus: true, required: :true, rows: 20, as: :text, :class => 'form-control' %>
  </div>

  <div class="hidden">
    <%= f.label :nickname %><br/>
    <%= f.text_field :nickname, hint: 'Nemojte ispunjavati ovo polje' %>
  </div>


  <%= f.submit "Pošalji poruku", :class => 'btn btn-primary' %>

<% end %>
-->
     <div class="container">         

        <div class="row">
          <div class="col-xs-10 col-sm-5 col-md-5 col-lg-5 col-xs-push-1">   
            <%= image_tag 'contact.svg', :class => 'hvr-grow', :id => 'contact' %>
            <h4>KONTAKT</h4>
            <%= form_for @contact, :html => {:id => "contact-form"} do |f| %> 
              <div class="form-group">       
                <label for=<%= :name %>>IME I PREZIME</label>
                <%= f.text_field :name, autofocus: true, required: :true, :class => 'form-control' %>           
              </div>

              <div class="form-group">       
                <label for=<%= :email %>>EMAIL</label>
                 <%= f.email_field :email, autofocus: true, required: :true, :class => 'form-control' %>
              </div>

              <div class="form-group">       
                <label for=<%= :message %>>PORUKA</label>
                <%= f.text_area :message, autofocus: true, required: :true, rows: 4, as: :text, :class => 'form-control' %>
              </div>

              <div class="hidden">
                <%= f.label :nickname %><br/>
                <%= f.text_field :nickname, hint: 'Nemojte ispunjavati ovo polje' %>
              </div>
              <%= f.submit "POŠALJI", :class => 'btn-contact' %>
            <% end %>
          </div>

          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-sm-push-2 col-md-push-2 col-lg-push-2" id="pages">   
            

            <div class="row">
                <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                   <%= image_tag 'pages.svg', :class => 'hvr-grow'%>
                </div>
                <div class="col-xs-6 col-sm-9 col-md-9 col-lg-9 col-sm-pull-2 col-md-pull-2 col-lg-pull-2">
                  <h5 id="pages-headline">STRANICE</h5>
                    <%= link_to "Početna", root_path %>
                    <%= link_to "O udruzi", about_path %>
                    <%= link_to "Statut", statut_path %>
                    <%= link_to "Vijesti", news_path %>
                    <%= link_to "Kontakt", contact_path %>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                  <%= image_tag 'location.svg', :class => 'hvr-grow', :id => 'location' %>
                </div>
                <div class="col-xs-6 col-sm-9 col-md-9 col-lg-9 col-sm-pull-2 col-md-pull-2 col-lg-pull-2">
                    <p>Udruga inženjera i diplomiranih inženjera <br>Fakulteta elektrotehinike, računarstva i informacijskih tehnologija
                    <br><br>Kneza Trpimira 2b<br>31000 Osijek<br>Hrvatska</p>
                </div>
            </div>

          </div>

          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-sm-push-3 col-md-push-3 col-lg-push-3">   
              
              <div class="row">
                  <div class="col-xs-3 col-sm-2 col-md-2 col-lg-2 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                    <%= image_tag 'social.svg', :class => 'hvr-grow', :id => 'social-img' %>
                  </div>
                  <div class="col-xs-6 col-sm-9 col-md-9 col-lg-9 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                    <h5 id="social-headline">SOCIAL</h5>
                  </div>
              </div>


              <div class="row">
                  <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                    <%= image_tag 'facebook.svg', :class => 'social-footer' %>
                  </div>
                  <div class="col-xs-6 col-sm-9 col-md-9 col-lg-9 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                     <a href="https://www.facebook.com/ama.etfos/" class="social-link">Facebook</a>
                  </div>
              </div>

              <div class="row">
                <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                  <%= image_tag 'twitter.svg', :class => 'social-footer' %>
                </div>
                 <div class="col-xs-6 col-sm-9 col-md-9 col-lg-9 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                  <a href="#" class="social-link">Twitter</a>
                </div>
              </div>


              <div class="row">
                <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                  <%= image_tag 'instagram.svg', :class => 'social-footer' %>
                </div>
                 <div class="col-xs-6 col-sm-9 col-md-9 col-lg-9 col-sm-pull-1 col-md-pull-1 col-lg-pull-1">
                  <a href="#" class="social-link">Instagram</a>
                </div>
              </div>
              
              <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-sm-pull-1 col-sm-pull-4 col-md-pull-4 col-lg-pull-4 col-sm-pull-4">
                  <%= image_tag 'logos.svg', :class => 'img-responsive', :id => 'footer-logos' %>
                </div>
              </div>

          </div>

         
          </div>
        </div>
    </div>
  </section>

  <section class="copyright">

     <div class="container">         
        <div class="row">
            <p class="text-center">Copyright AMA ETFOS 2016</p>    
        </div>
    </div>
  
  </section>

  <% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top nav-down" <% unless current_page?(root_path) %> id = 'navbar2' <% end%>>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= image_tag 'logo_brand.svg', :id => 'brand-logo' %>AMA ETFOS</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


          <ul class="nav navbar-nav navbar-right">
            
            <li class=<% if current_page?(root_path) %>'active'
            <% else %>'hvr-overline-from-center'<% end %>>
            <%= link_to "Početna", root_path %></li>
            
            <li class=<% if current_page?(about_path) %>'active'
            <% else %>'hvr-overline-from-center'<% end %>>
            <%= link_to "O udruzi", about_path %></li>
            
            <li class=<% if current_page?(statut_path) %>'active'
            <% else %>'hvr-overline-from-center'<% end %>>
            <%= link_to "Statut", statut_path %></li>
            
            <li class=<% if current_page?(news_path) %>'active'
            <% else %>'hvr-overline-from-center'<% end %>>
            <%= link_to "Vijesti", news_path %></li>
            
            <% if user_signed_in? %>
              <li class=<% if current_page?(show_profile_path) %>'active'
              <% else %>'hvr-overline-from-center'<% end %>>
              <%= link_to "Profil", show_profile_path %></li>
              <li><%= link_to "ODJAVA", logout_path %></li>
            <% else %>
                <li class=<% if current_page?(contact_path) %>'active'
              <% else %>'hvr-overline-from-center'<% end %>>
              <%= link_to "Kontakt", contact_path %></li>
              <li><%= link_to "PRIJAVA", login_path, :class => 'hvr-grow' %></li>
           <% end %> 
          </ul>
        </div>
</nav>

app/views/layouts/admin_layout.html.erb
 <!-- ADD SOME SIDE BAR NAVIGATION -->

<!DOCTYPE html>
<html id="admin-area">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'admins', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admins', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>

  <body>

    <% if admin_signed_in? %>
      <%= render 'layouts/admin_header' %>
    <% else %>
        <div class="container-fluid">
        <div class="col-md-4 col-md-offset-4">
    <% end %>



    <%= yield %>
        
    </div>

  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link href='https://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>


</head>
    <% unless (current_page?(user_session_path) || current_page?(register_path) || current_page?(login_path) || current_page?(new_user_session_path)) %>
      <body>
      <%= render 'layouts/header' %>
    <% end %>

    <!--
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    -->
		<%= yield %>

	<%= render 'layouts/footer' %>

</body>
</html>